-- Geo fields + distance/co2 tracking

ALTER TABLE public.shop
ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

ALTER TABLE public.client
ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

ALTER TABLE public.delivery
ADD COLUMN IF NOT EXISTS distance_km DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS co2_saved_kg DOUBLE PRECISION;
